import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// components
import Sidebar from "../components/Sidenav";

// providers
import ToasterProvider from "../providers/ToasterProvider";
import ModalProvider from "../providers/ModalProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <ModalProvider />
        <ToasterProvider />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
