import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// components
import Sidebar from "../components/Sidenav";

// providers
import ToasterProvider from "../providers/ToasterProvider";
import ModalProvider from "../providers/ModalProvider";
import { IHandleActionAnnouncement } from "../types/announcement";
import { createAnnouncement } from "../actions/announcements";
import { createClass, deleteClass, getAllByTeacher, getAllClasses, getClassById, partialUpdateClass } from "../actions/classes";
import { auth } from "../auth";
import { SessionProvider } from "next-auth/react";
import NotificationProvider from "../providers/NotificationProvider";
import { IHandleActionClass } from "../types/class";
import { ClassFormData, ClassFormDataPartialUpdate } from "../actions/classes/schemas";
import { extractUserIdFromBackEndToken } from "../utils";
import { IHandleActionCoordinator } from "../types/coordinator";
import { addStudentToClass, createTeachingAssignment, deleteTeachingAssignmentById, getTeachingAssignmentById, partialUpdateTeachingAssignment, removeStudentFromClass } from "../actions/coordinators";
import { TeachingAssignmentFormData, TeachingAssignmentFormDataPartialUpdate } from "../actions/coordinators/schemas";
import { IHandleActionTeacher } from "../types/teachers";
import { getAllTeachers } from "../actions/teachers";
import { IHandleActionSubject } from "../types/subject";
import { getAllSubjects } from "../actions/subjects";
import { IHandleActionStudent } from "../types/students";
import { getAllStudents } from "../actions/students";
import { IHandleActionUsers } from "../types/user";
import { deleteUserById, getUserById, updateUserById } from "../actions/users";
import { UserFormData } from "../actions/auth/schemas";
import { handleSignUp } from "../actions/auth";
import { UpdateUserFormData } from "../actions/users/schemas";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    const token = String(session?.backendToken);

    const handleActionsAnnouncement: IHandleActionAnnouncement = {
        handleActionCreate: async (data) => {
            "use server";
            return createAnnouncement(data, token);
        },
        handleActionGetClassesByTeacher: async () => {
            "use server";
            console.log('é o que: ', session?.user);
            const teacherId = extractUserIdFromBackEndToken(token);
            return getAllByTeacher(Number(teacherId), token);
        },
        handleActionGetAllClasses: async () => {
            "use server";
            return (await getAllClasses(token))?.data;
        },
    }

    const handleActionsClass: IHandleActionClass = {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        handleActionCreate: async (data: ClassFormData) => {
            "use server";
            return createClass(data, token);
        },
        handleActionPartialUpdate: async (classId: number, data: ClassFormDataPartialUpdate) => {
            "use server";
            return partialUpdateClass(classId, data, token);
        },
        handleActionGetById: async (classId: number, showRels: boolean = false) => {
            "use server";
            return getClassById(classId, token, showRels);
        },
        handleActionDeleteById: async (classId: number) => {
            "use server";
            return deleteClass(classId, token);
        }
    }

    const handleActionsCoordinator: IHandleActionCoordinator = {
        handleActionDeleteTeachingAssignmentById: async (teachingAssignmentId: number) => {
            "use server";
            return deleteTeachingAssignmentById(teachingAssignmentId, token);
        },
        handleActionCreateTeachingAssignment: async (classId: number, data: TeachingAssignmentFormData) => {
            "use server";
            return createTeachingAssignment(classId, data, token);
        },
        handleActionPartialUpdateTeachingAssignment: async (teachingAssignmentId: number, data: TeachingAssignmentFormDataPartialUpdate) => {
            "use server";
            return partialUpdateTeachingAssignment(teachingAssignmentId, data, token);
        },
        handleActionGetTeachingAssignmentById: async (teachingAssignmentId: number) => {
            "use server";
            return getTeachingAssignmentById(teachingAssignmentId, token);
        },
        handleActionAddStudentToClass: async (studentId: number, classId: number) => {
            "use server";
            return addStudentToClass(studentId, classId, token);
        },
        handleActionRemoveStudentFromClass: async (studentId: number, classId: number) => {
            "use server";
            return removeStudentFromClass(studentId, classId, token);
        },
    }

    const handleActionsTeacher: IHandleActionTeacher = {
        handleActionGetAll: async () => {
            "use server";
            return getAllTeachers(token);
        }
    }

    const handleActionsStudent: IHandleActionStudent = {
        handleActionGetAll: async (showRels?: boolean, excludeStudentsWithinClass?: boolean, onlyStudentWithClassId?: number) => {
            "use server";
            return getAllStudents(token, showRels, excludeStudentsWithinClass, onlyStudentWithClassId);
        }
    }

    const handleActionsSubject: IHandleActionSubject = {
        handleActionGetAll: async (classId?: number) => {
            "use server";
            return getAllSubjects(token, classId);
        }
    }

    const handleActionUser: IHandleActionUsers ={
        handleActionDeleteById: async (userId: number) => {
            "use server";
            return deleteUserById(userId, token);
        },
        handleActionCreateUser: async (userData: UserFormData) => {
            "use server";
            return handleSignUp(userData, token);
        },
        handleActionUpdateUserById: async (userId: number, userData: UpdateUserFormData) => {
            "use server";
            return updateUserById(userId, userData, token);
        },
        handleActionGetUserById: async (userId: number) => {
            "use server";
            return getUserById(userId, token);
        }
    }

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
            >
                <SessionProvider session={session}>
                    <NotificationProvider />
                    <ModalProvider
                        handleActionsAnnouncement={handleActionsAnnouncement}
                        handleActionsClass={handleActionsClass}
                        handleActionsCoordinator={handleActionsCoordinator}
                        handleActionsSubject={handleActionsSubject}
                        handleActionsTeacher={handleActionsTeacher}
                        handleActionsStudent={handleActionsStudent}
                        handleActionUser={handleActionUser}
                    />
                    <ToasterProvider />
                    {session && <Sidebar />}
                    <main className="flex justify-center items-center w-full">
                        {children}
                    </main>
                </SessionProvider>
            </body>
        </html>
    );
}
